import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "next-themes";
// import Topbar from "./components/dashboard/Topbar";
// import Sidebar from "./components/dashboard/Sidebar"; // Make sure you have Sidebar component
import ResponsiveSidebar from "./components/sidebar/ResponsiveSidebar";
import ResponsiveTopber from "./components/topber/ResponsiveTopber";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="flex  min-h-screen bg-gradient-to-br from-[#0d1b2a] to-[#1b263b] text-white w-full">
            {/* Sidebar on the left */}
            {/* <Sidebar /> */}
 <ResponsiveSidebar />
            {/* Main Content Area */}
            <div className="flex flex-col flex-1  ">
              {/* Topbar */}
             <ResponsiveTopber/>

              {/* Page Content */}
              <main className="p-4">{children}</main>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
